title: "clectric.diy"
description: "An online makerspace for the SynthDIY community."
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
analytics:
  provider: "google"
  google:
    tracking_id: "G-TJRSWGLQDX"
    anonymize_ip: true